-- premake5.lua

require "premake_modules/usage"
require "premake_modules/emscripten"
require "premake_modules/vscode"

IS_ANDROID = (_ACTION == "androidndk")

------------------------------------------

newoption {
   trigger     = "raspberry-pi",
   description = "adds specific define for compiling on Raspberry Pi"
}

-- JERICHO: comma-separated list of module ids (folders under ../mods) to
-- compile into the game. Example: --with-mods="example,crumple"
newoption {
   trigger     = "with-mods",
   value       = "LIST",
   description = "JERICHO modules to build (comma-separated ids, folders under ../mods)"
}

JERICHO_MODS = {}
if _OPTIONS["with-mods"] then
   for m in string.gmatch(_OPTIONS["with-mods"], "[^,%s]+") do
      table.insert(JERICHO_MODS, m)
   end
end

-- Generate JERICHO/gen/jer_registry.c listing the compiled-in modules.
-- The game project compiles this file; it declares each module's entry
-- (extern "C" so C modules link cleanly against the C++ game) and exposes
-- the id->entry table the runtime walks at boot.
local function jericho_generate_registry(mods)
   local dir = "Game/C/JERICHO/gen"
   local f

   os.mkdir(dir)

   f = io.open(dir .. "/jer_registry.c", "w")

   f:write("/* generated by premake5.lua -- do not edit */\n")
   f:write("#include \"jericho.h\"\n\n")
   f:write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n")

   for _, m in ipairs(mods) do
      f:write(string.format("void jer_module_%s_entry(JERICHO_CONTEXT* ctx);\n", m))
   end

   f:write("\n")
   -- extern: the registry TU is compiled as C++ (in the game project), where
   -- file-scope const has internal linkage by default; the whole table is
   -- inside extern \"C\" so the C runtime (JERICHO.lib) sees unmangled names
   f:write("extern const JER_REGISTRY_ENTRY jer_registry_modules[] = {\n")

   if #mods == 0 then
      -- C++ has no zero-size arrays: emit a NULL sentinel (count stays 0)
      f:write("\t{ NULL, NULL, 0 },\n")
   end

   for _, m in ipairs(mods) do
      -- default-enabled comes from the module's mod.toml (default true)
      local defaultEnabled = 1
      local toml = io.open(string.format("../mods/%s/mod.toml", m), "r")

      if toml then
         local line = toml:read("*l")

         while line do
            local v = line:match("default%-enabled%s*=%s*(%w+)")

            if v == "false" then
               defaultEnabled = 0
            end

            line = toml:read("*l")
         end

         toml:close()
      end

      f:write(string.format("\t{ \"%s\", jer_module_%s_entry, %d },\n", m, m, defaultEnabled))
   end

   f:write("};\n")
   f:write(string.format("extern const int jer_registry_module_count = %d;\n", #mods))
   f:write("#ifdef __cplusplus\n}\n#endif\n")
   f:close()
end

jericho_generate_registry(JERICHO_MODS)

-- Common include dirs/defines for anything that includes the game headers.
local function jer_game_includedirs()
   includedirs {
      "Game",
      "Game/C",
      "Game/C/JERICHO/include",
   }

   if os.target() == "emscripten" then
      includedirs {
         OPENAL_DIR.."/include",
         JPEG_DIR.."/",
      }
   end

   if os.target() == "windows" then
      includedirs {
         SDL2_DIR.."/include",
         OPENAL_DIR.."/include",
         JPEG_DIR.."/",
      }
   end

   if os.target() == "linux" then
      includedirs {
         "/usr/include/SDL2",
         OPENAL_DIR.."/include",
         JPEG_DIR.."/",
      }
   end
end

local function jer_common_defines()
   defines { GAME_REGION }
   defines { "BUILD_CONFIGURATION_STRING=\"%{cfg.buildcfg}\"" }

   -- deterministic JERICHO build version: git describe when available,
   -- otherwise a plain literal (each exe release = a new JERICHO version)
   local null = (os.target() == "windows") and "2>nul" or "2>/dev/null"
   local desc = ""
   local f = io.popen("git describe --tags --always --dirty " .. null)
   if f then
      desc = f:read("*l") or ""
      f:close()
   end
   if desc == nil or desc == "" then
      desc = "1.0.0"
   end
   defines { ("JERICHO_BUILD_VERSION=\"%s\""):format(desc) }
end

table.insert(premake.option.get("os").allowed, { "emscripten", "Emscripten" })

------------------------------------------

-- you can redefine dependencies
SDL2_DIR = os.getenv("SDL2_DIR") or "dependencies/SDL2-2.30.2"
OPENAL_DIR = os.getenv("OPENAL_DIR") or "dependencies/openal-soft-1.23.1-bin"
JPEG_DIR = os.getenv("JPEG_DIR") or "dependencies/jpeg-9d"

WEBDEMO_DIR = os.getenv("WEBDEMO_DIR") or "../../web_demo@/"	-- FIXME: make it better
RED2_DIR = os.getenv("RED2_DIR") or "../../data@/"
WEBSHELL_PATH = "../platform/Emscripten"	-- must be relative to makefile path (SADLY)

GAME_REGION = os.getenv("GAME_REGION") or "NTSC_VERSION" -- or PAL_VERSION
GAME_VERSION = os.getenv("APPVEYOR_BUILD_VERSION") or nil

if not (GAME_REGION == "NTSC_VERSION" or GAME_REGION == "PAL_VERSION") then
    error("'GAME_REGION' should be 'NTSC_VERSION' or 'PAL_VERSION'")
end

------------------------------------------
	
workspace "REDRIVER2"
	if _ACTION ~= "vscode" then
		if os.target() == "emscripten" then
    		location "build_web"
		else
    		location "build"
		end
	else
		-- setup VSCode generator settings
		vscode_makefile "build"
		vscode_launch_cwd ("${workspaceRoot}/../data")
		--vscode_launch_environment {	}
	end

    configurations { "Debug", "Release", "Release_dev" }
	
    defines { VERSION } 
	
	if os.target() == "emscripten" then
		platforms { "emscripten" }
	
		buildoptions {
			"-s USE_SDL=2",
			"-s USE_LIBJPEG=1",
			--"-s USE_WEBGL2=1",
			"-Wno-c++11-narrowing",
			"-Wno-constant-conversion",
			"-Wno-writable-strings",
			"-Wno-unused-value",
			"-Wno-switch",
			"-Wno-shift-op-parentheses",
			"-Wno-parentheses",
			"-Wno-format",
		}

		linkoptions  { 
			"-s TOTAL_MEMORY=1073741824",
			"-s USE_SDL=2",
			"-s USE_LIBJPEG=1",
			"-s FULL_ES2=1",
			--"-s USE_WEBGL2=1",
			"-s ASYNCIFY=1",
			"-s ALLOW_MEMORY_GROWTH=1",
			"-s GL_TESTING=1",
			("--shell-file " .. WEBSHELL_PATH .. "/shell.html"),
			("--preload-file " .. WEBDEMO_DIR),
			("--preload-file " .. RED2_DIR),
			"-s 'EXPORTED_RUNTIME_METHODS=[\"ccall\", \"writeArrayToMemory\"]'",
			"-s 'EXPORTED_FUNCTIONS=[\"_main\", \"_malloc\"]'"
		}
		
		filter { "kind:*App" }
			targetextension ".html"
			
		postbuildcommands {
			"{COPY} " .. WEBSHELL_PATH .. "/style.css %{cfg.buildtarget.directory}",
			"{COPY} " .. WEBSHELL_PATH .. "/lsfs.js %{cfg.buildtarget.directory}"
		}

	elseif IS_ANDROID then		
		system "android"
		shortcommands "On"
		
		platforms {
			"android-arm", "android-arm64"
		}
		
		disablewarnings {
			"c++11-narrowing",
			"constant-conversion",
			"writable-strings",
			"unused-value",
			"switch",
			"shift-op-parentheses",
			"parentheses",
			"format",
		}
		
		buildoptions {
			"-fpermissive",
			"-fexceptions",
			"-pthread",
		}
		
		linkoptions {
			"--no-undefined",
			"-fexceptions",
			"-pthread",
			
			"-mfloat-abi=softfp",	-- force NEON to be used
			"-mfpu=neon"
		}

		filter "platforms:*-x86"
			architecture "x86"

		filter "platforms:*-x64"
			architecture "x64"

		filter "platforms:*-arm"
			architecture "arm"

		filter "platforms:*-arm64"
			architecture "arm64"
	else
		platforms { "x86", "x64" }
	end
	
	startproject "REDRIVER2"
	
	configuration "raspberry-pi"
		defines { "__RPI__" }

	filter "system:Linux"
		buildoptions {
            "-Wno-narrowing",
			"-Wno-endif-labels",
			"-Wno-write-strings",
			"-Wno-format-security",
			"-Wno-unused-result",
            "-fpermissive"
        }
		
		cppdialect "C++11"
		
	filter {"system:Linux", "platforms:x86"}
		buildoptions { "-m32" }
		linkoptions { "-m32" }

	filter "system:Windows"
		disablewarnings { "4996", "4554", "4244", "4101", "4838", "4309" }

    filter "configurations:Debug"
        defines { 
            "_DEBUG", 
	        "DEBUG"
        }
        symbols "On"

    filter "configurations:Release"
        defines {
            "NDEBUG",
        }
		
	filter "configurations:Release_dev"
        defines {
            "NDEBUG",
        }
        symbols "On"
        
if os.target() == "windows" then
	include "premake_libjpeg.lua"
end

-- font tool
if os.target() ~= "emscripten" then
	include "premake5_font_tool.lua"
end

-- Psy-Cross layer
include "premake5_psycross.lua"



-- game iteslf
-- JERICHO runtime + compiled-in modules -----------------------------------
project "JERICHO"
	kind "StaticLib"
	language "c++"

	jer_common_defines()

	includedirs {
		"Game/C/JERICHO/include",
		"Game/C/JERICHO/src",
	}

	files {
		"Game/C/JERICHO/include/**.h",
		"Game/C/JERICHO/src/**.c",
		"Game/C/JERICHO/src/**.h",
	}

	targetdir "bin/%{cfg.buildcfg}"

	filter "system:Windows"
		disablewarnings { "4996", "4244", "4018", "4267" }

	filter "system:linux"
		buildoptions { "-Wno-unused-parameter" }

for _, JER_MOD in ipairs(JERICHO_MODS) do
	filter {}	-- reset any leaked filter (old premake leaks across project())

	project ("mod_" .. JER_MOD)
		kind "StaticLib"
		language "c++"

		jer_common_defines()
		jer_game_includedirs()

		uses {
			"PsyCross",
		}

		files {
			("../mods/" .. JER_MOD .. "/**.c"),
			("../mods/" .. JER_MOD .. "/**.h"),
		}

		includedirs {
			("../mods/" .. JER_MOD),
		}

		targetdir "bin/%{cfg.buildcfg}"

		filter "system:Windows"
			disablewarnings { "4996", "4244", "4018", "4267", "4101", "4013" }

		filter "system:linux"
			buildoptions { "-Wno-unused-parameter", "-Wno-unused-variable" }

		-- the game compiles all C as C++ (headers rely on C++ struct-tag
		-- rules); modules must match
		filter { "files:**.c", "files:**.C" }
			compileas "C++"
end

filter {}	-- reset any leaked filter (old premake leaks across project())

project "REDRIVER2"
    kind "WindowedApp"

    language "c++"
    targetdir "bin/%{cfg.buildcfg}"

    includedirs { 
        "Game", 
        "Game/C/JERICHO/include",
    }
	
	uses { 
		"PsyCross",
	}

    defines { GAME_REGION }
	defines { "BUILD_CONFIGURATION_STRING=\"%{cfg.buildcfg}\"" }

    links { "JERICHO" }
    dependson { "JERICHO" }

	for _, JER_MOD in ipairs(JERICHO_MODS) do
		links { ("mod_" .. JER_MOD) }
		dependson { ("mod_" .. JER_MOD) }
	end

	filter {}	-- reset before the unfiltered settings below

	if GAME_VERSION ~= nil then
		local resVersion = string.gsub(GAME_VERSION, "%.", ",")
		defines{ "GAME_VERSION_N=\""..GAME_VERSION.."\"" }
		defines{ "GAME_VERSION_RES="..resVersion.."" }
	end

    files {
        "Game/**.h",
        "Game/**.c",
        "Game/C/JERICHO/gen/jer_registry.c",
    }

    -- the JERICHO SDK has its own project; don't double-compile it here
    excludes {
        "Game/C/JERICHO/src/**.c",
        "Game/C/JERICHO/src/**.h",
        "Game/C/JERICHO/include/**.h",
        "Game/C/JERICHO/test/**.c",
    }

    filter {"system:Windows or linux or platforms:emscripten"}
        --dependson { "PsyX" }
        links { "jpeg" }
				
		files {
			"utils/**.h",
			"utils/**.cpp",
			"utils/**.c",
			"redriver2_psxpc.cpp",
		}
		
	filter "platforms:emscripten"
	    includedirs { 
			OPENAL_DIR.."/include",
			JPEG_DIR.."/",
        }
		files { 
            "platform/Emscripten/*.cpp",
        }

    filter "system:Windows"
		entrypoint "mainCRTStartup"
		
		files { -- TEMP
			"platform/Emscripten/*.h",
			"platform/Emscripten/*.css",
			"platform/Emscripten/*.html", 
        }
		
        files { 
            "platform/Windows/resource.h", 
            "platform/Windows/Resource.rc", 
            "platform/Windows/main.ico" 
        }

        includedirs { 
            SDL2_DIR.."/include",
            OPENAL_DIR.."/include",
			JPEG_DIR.."/",
        }

        links { 
            "opengl32",
            "SDL2", 
            "OpenAL32",
        }

    filter {"system:Windows", "platforms:x86"}
        libdirs { 
            SDL2_DIR.."/lib/x86",
            OPENAL_DIR.."/libs/Win32",
        }

    filter {"system:Windows", "platforms:x64"}
        libdirs { 
            SDL2_DIR.."/lib/x64",
            OPENAL_DIR.."/libs/Win64",
        }

    filter "system:Windows"
        linkoptions {
			"/SAFESEH:NO", -- Image Has Safe Exception Handers: No. Because of openal-soft
        }
        
    filter "system:linux"
        includedirs {
            "/usr/include/SDL2"
        }

        links {
            "GL",
            "openal",
            "SDL2",
            "dl",
        }

    filter "configurations:Debug"
		targetsuffix "_dbg"
        defines { 
            "DEBUG_OPTIONS",
            "COLLISION_DEBUG",
			"CUTSCENE_RECORDER"
         }
		 symbols "On"

    filter "configurations:Release"
        optimize "Speed"
		
	filter "configurations:Release_dev"
		targetsuffix "_dev"
        defines { 
            "DEBUG_OPTIONS",
            "COLLISION_DEBUG",
			"CUTSCENE_RECORDER"
        }
        optimize "Speed"

    filter { "files:**.c", "files:**.C" }
        compileas "C++"
