/*
 * gen_exports.c — JERICHO mod-host tool.
 *
 * Parses an MSVC linker .map file and emits an exports.def listing every
 * public (external) symbol of the game exe, so mod DLLs can link against
 * the exe's import library and call game functions / read game globals
 * directly (e.g. player[], car_data[]) — without the game source.
 *
 * Usage: gen_exports <in.map> <out.def>
 *
 * Map structure (VS2019 /MAP):
 *   - "Start Length Name Class" — section table: each row maps a segment
 *     number to a section name and class (CODE = code, DATA = data).
 *   - "Address Publics by Value" — every external symbol:
 *         seg:off  name  rva+base  [kind]  lib:object
 *     (the single-letter kind column — 'f' = function — is present on some
 *     rows and absent on others; the section class is the reliable signal)
 *   A symbol whose segment is a CODE section is a function; everything
 *   else is data (exported with the "DATA" keyword so MSVC exports it).
 *   Linker-generated rows (segment 0000) and symbols that live in CRT/DLL
 *   import stubs (which cannot be exported) are skipped.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_SEGMENTS 64
#define MAX_LINE 4096
#define MAX_NAME 1024
#define MAX_TOKENS 12

typedef struct
{
	int num;
	int isCode;
} SEG_CLASS;

static SEG_CLASS gSegs[MAX_SEGMENTS];
static int gSegCount;

static int segIsCode(int num)
{
	int i;

	for (i = 0; i < gSegCount; i++)
	{
		if (gSegs[i].num == num)
			return gSegs[i].isCode;
	}

	return -1;	/* unknown segment (linker-generated rows) */
}

/* Only symbols that live in the game's own code, the JERICHO SDK or the
 * compiled-in mod libraries (mod_*) are exported. PsyCross/jpeg internals
 * and CRT/DLL import stubs are excluded: addons talk to the engine through
 * the game's public symbols + the JERICHO API, and keeping the list ~3k
 * symbols stays under the MSVC linker's implib-generation limit
 * (LNK1000/LNK1106 above ~4k exports). */
static int jerSkipObj(const char* obj)
{
	char lib[64];
	const char* colon;
	size_t n;

	if (obj == NULL)
		return 1;

	if (obj[0] == '<')
		return 1;	/* <absolute> / <linker-defined> rows */

	colon = strchr(obj, ':');

	if (colon == NULL)
		return 0;	/* the game's own objects (no library prefix) */

	n = (size_t)(colon - obj);

	if (n >= sizeof(lib))
		n = sizeof(lib) - 1;

	memcpy(lib, obj, n);
	lib[n] = 0;

	return strcmp(lib, "JERICHO") != 0 && strncmp(lib, "mod_", 4) != 0;
}

int main(int argc, char** argv)
{
	FILE *in, *out;
	char line[MAX_LINE];
	char lastName[MAX_NAME] = "";
	int inSections = 0, inPublics = 0, emitted = 0;
	int maxExports = 0;	/* 0 = unlimited (used to find the linker ceiling) */

	if (argc < 3)
	{
		fprintf(stderr, "usage: gen_exports <in.map> <out.def> [maxExports]\n");
		return 2;
	}

	if (argc >= 4)
		maxExports = atoi(argv[3]);

	in = fopen(argv[1], "r");
	if (!in) { perror(argv[1]); return 2; }
	out = fopen(argv[2], "w");
	if (!out) { perror(argv[2]); return 2; }

	fprintf(out, "; generated by gen_exports from %s -- do not edit\n", argv[1]);
	fprintf(out, "; every public symbol of the game exe, for mod DLL linking\n");
	fprintf(out, "EXPORTS\n");

	while (fgets(line, sizeof line, in))
	{
		size_t len = strlen(line);
		while (len && (line[len - 1] == '\n' || line[len - 1] == '\r'))
			line[--len] = '\0';

		/* --- section table: seg:off  lenH  name  CODE|DATA --- */
		if (!inSections && strncmp(line, " Start", 6) == 0 && strstr(line, "Length") != NULL)
		{
			inSections = 1;
			continue;
		}

		if (inSections)
		{
			if (strstr(line, "Publics by Value") != NULL)
			{
				inSections = 0;
				inPublics = 1;
				continue;
			}

			{
				int seg;
				char lenHex[32];
				char secName[128];
				char cls[16];

				if (sscanf(line, " %4x:%*8x %31s %127s %15s", &seg, lenHex, secName, cls) == 4 &&
					gSegCount < MAX_SEGMENTS)
				{
					gSegs[gSegCount].num = seg;
					gSegs[gSegCount].isCode = (strcmp(cls, "CODE") == 0);
					gSegCount++;
				}
			}

			continue;
		}

		/* --- "Address Publics by Value" symbol rows --- */
		if (inPublics)
		{
			char* tok[MAX_TOKENS];
			int ntok = 0;
			int seg;
			int isCode;
			const char* name;
			const char* obj;
			int kindFn = 0;

			if (strncmp(line, " Static symbols", 15) == 0)
				break;		/* publics done */

			{
				char* p = line;

				while (*p != 0 && ntok < MAX_TOKENS)
				{
					while (*p == ' ' || *p == '\t')
						p++;

					if (*p == 0)
						break;

					tok[ntok++] = p;

					while (*p != 0 && *p != ' ' && *p != '\t')
						p++;

					if (*p != 0)
						*p++ = 0;
				}
			}

			/* shape: seg:off name rva [kind] lib:object */
			if (ntok < 4)
				continue;

			if (sscanf(tok[0], "%4x:%*8x", &seg) != 1)
				continue;

			name = tok[1];

			isCode = segIsCode(seg);

			if (isCode < 0)
				continue;	/* linker-generated row (segment 0000) */

			if (ntok >= 5 && strlen(tok[3]) == 1 &&
				(tok[3][0] == 'f' || tok[3][0] == 'F'))
				kindFn = 1;

			/* the object is the last token (may contain spaces -> joined) */
			obj = tok[ntok - 1];

			if (jerSkipObj(obj))
				continue;

			if (strcmp(name, lastName) == 0)
				continue;	/* dedupe (COMDAT folds) */

			/* deleting destructors (??_EClass@@ / ??_GClass@@) are
			 * compiler-generated and cannot be safely exported (LNK4102) */
			if (name[0] == '?' && name[1] == '?' && name[2] == '_' &&
				(name[3] == 'E' || name[3] == 'G'))
				continue;

			/* string-literal COMDATs (??_C@...) are compiler-generated and
			 * useless to mod DLLs; they churn on EVERY rebuild (time.c's
			 * __DATE__/__TIME__ change each compile), so a committed def
			 * would go stale and break the link */
			if (name[0] == '?' && name[1] == '?' && name[2] == '_' &&
				name[3] == 'C' && name[4] == '@')
				continue;

			fprintf(out, "\t%s%s\n", name, (isCode || kindFn) ? "" : " DATA");
			emitted++;

			if (maxExports > 0 && emitted >= maxExports)
				break;

			snprintf(lastName, sizeof(lastName), "%s", name);
		}
	}

	fclose(in);
	fclose(out);

	fprintf(stderr, "gen_exports: wrote %d symbol(s) to %s\n", emitted, argv[2]);
	return 0;
}
