<#
.SYNOPSIS
  Build, package and optionally publish a REDRIVER2 release locally.

.DESCRIPTION
  Local equivalent of the `windows` + `publish` jobs in
  .github/workflows/build.yml, for when GitHub Actions cannot run at all --
  e.g. the account is locked for a billing issue, so no runner ever starts
  and no release is produced.

  What it does, in the same order and with the same layout as CI:

    1. (re)generate the project files with premake (vs2019 locally)
    2. build Release and Release_dev for x64, each with the two-pass
       exports.def recipe CI uses -- see the note below
    3. stage data/ plus the runtime DLLs next to each exe and zip it as
       REDRIVER2_<cfg>_win64.zip
    4. with -Publish, create or refresh a GitHub release through the REST API
       and attach the zips

  Linux artifacts can ONLY come from CI: this script has no Linux toolchain.
  Run it and CI side by side -- the release simply carries whatever it got.

  Why two passes per config: exports.def is generated by gen_exports from a
  linker map, so any committed copy is stale by construction, yet the linker
  is handed it for EVERY configuration and architecture. Linking a config
  against a stale def fails with hundreds of LNK2001s. So: link once against
  a throwaway empty def (that is what writes the .map), regenerate the def
  from that map, then relink -- incremental, only the exe.

.PARAMETER Tag
  Release tag to publish to. Default 'alpha', the rolling pre-release the
  workflow refreshes on every push to main. Use a v* tag for a permanent
  release.

.PARAMETER Repo
  owner/name on GitHub. Default Njurse/JERICHO.

.PARAMETER Configuration
  Configs to build and package. Default both.

.PARAMETER OutDir
  Where the zips are written. Default 'dist'.

.PARAMETER Publish
  Actually publish. Without it the script builds and packages only, so you
  can inspect the artifacts first. -DryRun is the same thing spelled out.

.PARAMETER DryRun
  Build and package, print exactly what would be published, publish nothing.

.PARAMETER SkipBuild
  Skip the build and (re)package whatever is already staged. Handy when
  re-publishing an unchanged build.

.PARAMETER LanPackage
  Also build REDRIVER2_mp_lan.7z (the partner-facing LAN package with its own
  launchers) into -OutDir, so the release carries it too. Needs 7-Zip.

.EXAMPLE
  # see what a release would contain, publish nothing
  pwsh -File tools/publish_release.ps1 -DryRun

.EXAMPLE
  # refresh the rolling alpha
  $env:GH_TOKEN = 'ghp_...'
  pwsh -File tools/publish_release.ps1 -Publish

.EXAMPLE
  # permanent release from a tag
  pwsh -File tools/publish_release.ps1 -Tag v1.2.0 -Publish
#>
[CmdletBinding()]
param(
    [string]   $Tag = 'alpha',
    [string]   $Repo = 'Njurse/JERICHO',
    [string[]] $Configuration = @('Release', 'Release_dev'),
    [string]   $OutDir = 'dist',
    [switch]   $Publish,
    [switch]   $DryRun,
    [switch]   $SkipBuild,
    [switch]   $LanPackage
)

$ErrorActionPreference = 'Stop'

if ($DryRun) { $Publish = $false }

$RepoRoot  = Split-Path -Parent $PSScriptRoot
$SrcRebuild = Join-Path $RepoRoot 'src_rebuild'
$OutPath   = Join-Path $RepoRoot $OutDir

function Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Warn($msg) { Write-Host "!!  $msg" -ForegroundColor Yellow }
function Fail($msg) { Write-Host "!!  $msg" -ForegroundColor Red; exit 1 }

# --- locate MSBuild (vswhere first, PATH second) ---------------------------
function Get-MSBuild {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
    if (Test-Path $vswhere) {
        $found = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild `
                            -find 'MSBuild\**\Bin\MSBuild.exe' 2>$null | Select-Object -First 1
        if ($found -and (Test-Path $found)) { return $found }
    }
    $cmd = Get-Command msbuild -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    Fail "MSBuild not found. Install Visual Studio with the C++ workload, or run from a Developer prompt."
}

# --- 1. project files ------------------------------------------------------
function New-ProjectFiles {
    Step "Generating project files (premake vs2019)"
    $premake = Join-Path $SrcRebuild 'premake5.exe'
    if (-not (Test-Path $premake)) { Fail "premake5.exe not found in src_rebuild." }

    # premake reads the dependency locations from the environment. Set them
    # with the quoted `set "VAR=..."` form: an unquoted value keeps a trailing
    # space and premake then fails to find the dependency.
    $env:SDL2_DIR   = Join-Path $SrcRebuild 'dependencies\SDL2-2.30.2'
    $env:OPENAL_DIR = Join-Path $SrcRebuild 'dependencies\openal-soft-1.23.1-bin'
    $env:JPEG_DIR   = Join-Path $SrcRebuild 'dependencies\jpeg-9d'

    Push-Location $SrcRebuild
    try {
        & $premake vs2019 | Out-Null
        if ($LASTEXITCODE -ne 0) { Fail "premake failed ($LASTEXITCODE)." }
    } finally { Pop-Location }
}

# --- 2. build (two passes per config) --------------------------------------
function Invoke-Build {
    param([string] $MsBuild)

    foreach ($cfg in $Configuration) {
        $exe = if ($cfg -eq 'Release') { 'REDRIVER2' } else { 'REDRIVER2_dev' }
        $sln = Join-Path $SrcRebuild 'build\REDRIVER2.sln'
        $def = Join-Path $SrcRebuild 'exports.def'

        Step "Building $cfg (pass 1: empty def, emits the .map)"
        Set-Content -Path $def -Value 'EXPORTS' -Encoding ascii
        & $MsBuild $sln "/p:Configuration=$cfg" /p:Platform=x64 /m /nologo /v:m
        if ($LASTEXITCODE -ne 0) { Fail "pass 1 for $cfg failed ($LASTEXITCODE)." }

        Step "Regenerating exports.def for $cfg and relinking (pass 2)"
        $gen  = Join-Path $SrcRebuild "bin\$cfg\gen_exports.exe"
        $map  = Join-Path $SrcRebuild "bin\$cfg\$exe.map"
        if (-not (Test-Path $gen)) { Fail "gen_exports.exe missing for $cfg -- did pass 1 link?" }
        if (-not (Test-Path $map)) { Fail "$exe.map missing for $cfg -- is /MAP still on the link line?" }
        & $gen $map $def
        if ($LASTEXITCODE -ne 0) { Fail "gen_exports failed for $cfg ($LASTEXITCODE)." }

        & $MsBuild $sln "/p:Configuration=$cfg" /p:Platform=x64 /m /nologo /v:m
        if ($LASTEXITCODE -ne 0) { Fail "pass 2 for $cfg failed ($LASTEXITCODE)." }

        $exePath = Join-Path $SrcRebuild "bin\$cfg\$exe.exe"
        if (-not (Test-Path $exePath)) { Fail "$exe.exe was not produced." }
        Write-Host "    built $exePath"
    }
}

# --- 3. package ------------------------------------------------------------
function New-Package {
    if (Test-Path $OutPath) { Remove-Item $OutPath -Recurse -Force }
    New-Item -ItemType Directory -Path $OutPath | Out-Null

    $data = Join-Path $RepoRoot 'data'

    foreach ($cfg in $Configuration) {
        Step "Packaging $cfg"
        $bin = Join-Path $SrcRebuild "bin\$cfg"
        $exe = if ($cfg -eq 'Release') { 'REDRIVER2' } else { 'REDRIVER2_dev' }

        # Curate the payload instead of zipping the build directory: a local
        # bin/<cfg> is a working tree that also holds DRIVER/, 1.5 GB of FMV,
        # a copy of the original assets, screenshots and logs. CI zips a fresh
        # checkout, where bin/<cfg> is just what the build produced plus
        # data/*. Assemble exactly that, so a local release matches a CI one,
        # stays small, and deliberately ships no FMV.
        $stage = Join-Path $env:TEMP "rd2_pkg_$cfg"
        if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
        New-Item -ItemType Directory -Path $stage | Out-Null

        # the runtime data tree, as committed
        Copy-Item (Join-Path $data '*') $stage -Recurse -Force
        # the exe, and the mod mirror the post-build step wrote
        Copy-Item (Join-Path $bin "$exe.exe") $stage -Force
        if (Test-Path (Join-Path $bin 'JERICHO')) {
            Copy-Item (Join-Path $bin 'JERICHO') $stage -Recurse -Force
        }
        # runtime DLLs next to the exe (x64), as CI does
        Copy-Item (Join-Path $env:SDL2_DIR   'lib\x64\SDL2.dll') $stage -Force
        Copy-Item (Join-Path $env:OPENAL_DIR 'bin\Win64\soft_oal.dll') $stage -Force
        Copy-Item (Join-Path $env:OPENAL_DIR 'bin\Win64\soft_oal.dll') (Join-Path $stage 'OpenAL32.dll') -Force

        $zip = Join-Path $OutPath "REDRIVER2_${cfg}_win64.zip"
        Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -Force
        Remove-Item $stage -Recurse -Force
        Write-Host ("    {0}  ({1:N1} MB)" -f (Split-Path -Leaf $zip), ((Get-Item $zip).Length / 1MB))
    }
}

# --- 3b. the partner-facing LAN package (optional) -------------------------
function New-LanPackage {
    $script = Join-Path $RepoRoot 'JERICHO\MODS\mp\tools\pack_lan\make_lan_package.bat'
    if (-not (Test-Path $script)) {
        Warn "-LanPackage: $script not found, skipping"
        return
    }
    Step "Building the LAN package (REDRIVER2_mp_lan.7z)"
    $out = Join-Path $OutPath 'REDRIVER2_mp_lan.7z'
    & cmd /c "`"$script`" `"$out`""
    if ($LASTEXITCODE -ne 0) { Fail "make_lan_package.bat failed ($LASTEXITCODE)." }
}

# --- 4. publish (GitHub REST) ----------------------------------------------
function Get-GitHubHeaders {
    if (-not $env:GH_TOKEN) {
        Fail @"
GH_TOKEN is not set, so nothing can be published.

  Create a token with the 'repo' scope at
    https://github.com/settings/tokens
  then set it for this shell:

    `$env:GH_TOKEN = 'ghp_...'

  Re-run with -DryRun to build and package without publishing.
"@
    }
    return @{
        Authorization = "Bearer $($env:GH_TOKEN)"
        Accept        = 'application/vnd.github+json'
        'User-Agent'  = 'publish_release.ps1'
    }
}

function Invoke-Publish {
    $headers = Get-GitHubHeaders

    $commit = (& git -C $RepoRoot rev-parse --short HEAD 2>$null)
    if ($LASTEXITCODE -ne 0) { $commit = 'unknown' }
    $dirty = (& git -C $RepoRoot status --porcelain 2>$null)
    if ($dirty) { Warn "working tree has uncommitted changes -- the build will not match commit $commit" }

    $isAlpha = $Tag -eq 'alpha'
    $api   = "https://api.github.com/repos/$Repo"

    # does the release already exist? (the rolling alpha always will)
    $release = $null
    try {
        $release = Invoke-RestMethod -Method Get -Uri "$api/releases/tags/$Tag" -Headers $headers
    } catch {
        # 404 simply means the release does not exist yet
        $code = 0
        if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
        if ($code -ne 404) { throw }
    }

    if (-not $release) {
        Step "Creating release $Tag"
        $prerelease = if ($isAlpha) { $true } else { $false }
        $latest     = if ($isAlpha) { 'false' } else { 'true' }
        $title      = if ($isAlpha) { 'Alpha (rolling)' } else { $Tag }
        $body = @{
            tag_name    = $Tag
            name        = $title
            body        = "Built locally from $commit. Not a stable release - download and test at your own risk."
            prerelease  = $prerelease
            make_latest = $latest
        } | ConvertTo-Json
        $release = Invoke-RestMethod -Method Post -Uri "$api/releases" -Headers $headers `
                                     -Body $body -ContentType 'application/json'
    } else {
        Step "Refreshing existing release $Tag"
    }

    $files = Get-ChildItem $OutPath -File
    if (-not $files) { Fail "nothing to publish in $OutDir." }

    # replace assets with the same name -- the names repeat on every refresh
    foreach ($asset in @($release.assets)) {
        if ($files.Name -contains $asset.name) {
            Invoke-RestMethod -Method Delete -Uri "$api/releases/assets/$($asset.id)" -Headers $headers | Out-Null
            Write-Host "    replaced $($asset.name)"
        }
    }

    foreach ($file in $files) {
        Write-Host "    uploading $($file.Name)"
        $upload = "https://uploads.github.com/repos/$Repo/releases/$($release.id)/assets?name=$([uri]::EscapeDataString($file.Name))"
        Invoke-RestMethod -Method Post -Uri $upload -Headers $headers `
                          -ContentType 'application/octet-stream' -InFile $file.FullName | Out-Null
    }

    Write-Host "`nPublished: https://github.com/$Repo/releases/tag/$Tag" -ForegroundColor Green
}

# --- main ------------------------------------------------------------------
Write-Host "REDRIVER2 release -- repo $Repo, tag $Tag, configs $($Configuration -join ', ')" -ForegroundColor Green

if (-not $SkipBuild) {
    $msbuild = Get-MSBuild
    Write-Host "    msbuild: $msbuild"
    New-ProjectFiles
    Invoke-Build -MsBuild $msbuild
} else {
    Warn "-SkipBuild: reusing whatever is already built"
    $env:SDL2_DIR   = Join-Path $SrcRebuild 'dependencies\SDL2-2.30.2'
    $env:OPENAL_DIR = Join-Path $SrcRebuild 'dependencies\openal-soft-1.23.1-bin'
}

New-Package
if ($LanPackage) { New-LanPackage }

Step "Packaged into $OutDir"
Get-ChildItem $OutPath -File | ForEach-Object { Write-Host ("    {0}" -f $_.Name) }

if ($Publish) {
    Invoke-Publish
} else {
    Write-Host "`nNothing published (-DryRun or no -Publish)." -ForegroundColor Yellow
    Write-Host "Re-run with -Publish and GH_TOKEN set to attach these to the release." -ForegroundColor Yellow
}
